name: Run Cron Messages
on:
  push:
    branches:
      - 'test-weekly'

jobs:
  sendWeekly:
    name: weekly ping
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: execute python script # run the run.py to get the latest data
        run: |
          python3 -m pip install --upgrade pip
          pip install requests
          echo -e "import requests\nimport os\nurl = os.environ['DISCORD_WEBHOOK']\nresponse = requests.post(url, json={'content': 'https://weekly.antarcticsolutions.ca/'})" | python
